// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
)

type Category struct {
	ID           string
	Name         string
	Slug         string
	IsAnswerable int64
	UpdatedAt    string
}

type Discussion struct {
	Number         int64
	Title          string
	Url            string
	State          string
	CreatedAt      string
	UpdatedAt      string
	ClosedAt       sql.NullString
	Author         string
	CategoryName   string
	AnswerChosenAt sql.NullString
	AnsweredBy     sql.NullString
	Labels         json.RawMessage
	Body           sql.NullString
	UpvoteCount    sql.NullInt64
	AnswerChosenBy sql.NullString
}

type DiscussionComment struct {
	DiscussionNumber int64
	ID               string
	CreatedAt        string
	UpdatedAt        string
	Author           string
	ReplyTo          sql.NullString
	Body             sql.NullString
	UpvoteCount      sql.NullInt64
}

type Issue struct {
	Number      int64
	Title       string
	Url         string
	State       string
	StateReason sql.NullString
	CreatedAt   string
	UpdatedAt   string
	ClosedAt    sql.NullString
	Author      string
	Labels      json.RawMessage
	Body        sql.NullString
	Locked      int64
	Reactions   json.RawMessage
}

type IssueComment struct {
	IssueNumber int64
	ID          string
	CreatedAt   string
	UpdatedAt   string
	Author      string
	Body        sql.NullString
}

type PullRequest struct {
	Number         int64
	Title          string
	Url            string
	State          string
	CreatedAt      string
	UpdatedAt      string
	ClosedAt       sql.NullString
	MergedAt       sql.NullString
	Author         string
	Labels         json.RawMessage
	Body           sql.NullString
	IsDraft        int64
	HeadRefName    string
	BaseRefName    string
	ReviewDecision sql.NullString
	Additions      int64
	Deletions      int64
	ChangedFiles   int64
}
