// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
)

const findKnownDiscussions = `-- name: FindKnownDiscussions :many
select
    number
from
    discussions
`

func (q *Queries) FindKnownDiscussions(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, findKnownDiscussions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var number int64
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMostRecentlyUpdatedDiscussion = `-- name: FindMostRecentlyUpdatedDiscussion :one
select
    updated_at
from
    discussions
limit
    1
`

func (q *Queries) FindMostRecentlyUpdatedDiscussion(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, findMostRecentlyUpdatedDiscussion)
	var updated_at string
	err := row.Scan(&updated_at)
	return updated_at, err
}

const findUpdatedTimesForDiscussions = `-- name: FindUpdatedTimesForDiscussions :many
select
    number,
    updated_at
from
    discussions
where
    number in (/*SLICE:numbers*/?)
`

type FindUpdatedTimesForDiscussionsRow struct {
	Number    int64
	UpdatedAt string
}

func (q *Queries) FindUpdatedTimesForDiscussions(ctx context.Context, numbers []int64) ([]FindUpdatedTimesForDiscussionsRow, error) {
	query := findUpdatedTimesForDiscussions
	var queryParams []interface{}
	if len(numbers) > 0 {
		for _, v := range numbers {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:numbers*/?", strings.Repeat(",?", len(numbers))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:numbers*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUpdatedTimesForDiscussionsRow
	for rows.Next() {
		var i FindUpdatedTimesForDiscussionsRow
		if err := rows.Scan(&i.Number, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDiscussion = `-- name: InsertDiscussion :exec
insert into
    discussions (
        number,
        title,
        url,
        state,
        created_at,
        updated_at,
        closed_at,
        author,
        category_name,
        answer_chosen_at,
        answer_chosen_by,
        answered_by,
        labels,
        body,
        upvote_count
    )
values
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) on conflict(number) do
update
set
    title = excluded.title,
    url = excluded.url,
    state = excluded.state,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    closed_at = excluded.closed_at,
    author = excluded.author,
    category_name = excluded.category_name,
    answer_chosen_at = excluded.answer_chosen_at,
    answer_chosen_by = excluded.answer_chosen_by,
    answered_by = excluded.answered_by,
    labels = excluded.labels,
    body = excluded.body,
    upvote_count = excluded.upvote_count
`

type InsertDiscussionParams struct {
	Number         int64
	Title          string
	Url            string
	State          string
	CreatedAt      string
	UpdatedAt      string
	ClosedAt       sql.NullString
	Author         string
	CategoryName   string
	AnswerChosenAt sql.NullString
	AnswerChosenBy sql.NullString
	AnsweredBy     sql.NullString
	Labels         json.RawMessage
	Body           sql.NullString
	UpvoteCount    sql.NullInt64
}

func (q *Queries) InsertDiscussion(ctx context.Context, arg InsertDiscussionParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscussion,
		arg.Number,
		arg.Title,
		arg.Url,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ClosedAt,
		arg.Author,
		arg.CategoryName,
		arg.AnswerChosenAt,
		arg.AnswerChosenBy,
		arg.AnsweredBy,
		arg.Labels,
		arg.Body,
		arg.UpvoteCount,
	)
	return err
}

const insertDiscussionComment = `-- name: InsertDiscussionComment :exec
insert into
    discussion_comments (
        discussion_number,
        id,
        created_at,
        updated_at,
        author,
        reply_to,
        body,
        upvote_count
    )
values
    (?, ?, ?, ?, ?, ?, ?, ?) on conflict(id) do
update
set
    id = excluded.id,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    author = excluded.author,
    reply_to = excluded.reply_to,
    body = excluded.body,
    upvote_count = excluded.upvote_count
`

type InsertDiscussionCommentParams struct {
	DiscussionNumber int64
	ID               string
	CreatedAt        string
	UpdatedAt        string
	Author           string
	ReplyTo          sql.NullString
	Body             sql.NullString
	UpvoteCount      sql.NullInt64
}

func (q *Queries) InsertDiscussionComment(ctx context.Context, arg InsertDiscussionCommentParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscussionComment,
		arg.DiscussionNumber,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Author,
		arg.ReplyTo,
		arg.Body,
		arg.UpvoteCount,
	)
	return err
}
