// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
)

const findKnownDiscussions = `-- name: FindKnownDiscussions :many
select
    number
from
    discussions
where
    number in (/*SLICE:numbers*/?)
`

func (q *Queries) FindKnownDiscussions(ctx context.Context, numbers []int64) ([]int64, error) {
	query := findKnownDiscussions
	var queryParams []interface{}
	if len(numbers) > 0 {
		for _, v := range numbers {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:numbers*/?", strings.Repeat(",?", len(numbers))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:numbers*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var number int64
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDiscussion = `-- name: InsertDiscussion :exec
insert into
    discussions (
        number,
        title,
        url,
        state,
        created_at,
        updated_at,
        closed_at,
        author,
        category_name,
        answer_chosen_at,
        answered_by,
        labels
    )
values
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDiscussionParams struct {
	Number         int64
	Title          string
	Url            string
	State          string
	CreatedAt      string
	UpdatedAt      string
	ClosedAt       string
	Author         string
	CategoryName   string
	AnswerChosenAt sql.NullString
	AnsweredBy     sql.NullString
	Labels         json.RawMessage
}

func (q *Queries) InsertDiscussion(ctx context.Context, arg InsertDiscussionParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscussion,
		arg.Number,
		arg.Title,
		arg.Url,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ClosedAt,
		arg.Author,
		arg.CategoryName,
		arg.AnswerChosenAt,
		arg.AnsweredBy,
		arg.Labels,
	)
	return err
}

const insertDiscussionComment = `-- name: InsertDiscussionComment :exec
insert into
    discussion_comments (
        discussion_number,
        id,
        created_at,
        updated_at,
        author,
        reply_to
    )
values
    (?, ?, ?, ?, ?, ?)
`

type InsertDiscussionCommentParams struct {
	DiscussionNumber int64
	ID               string
	CreatedAt        string
	UpdatedAt        string
	Author           string
	ReplyTo          sql.NullString
}

func (q *Queries) InsertDiscussionComment(ctx context.Context, arg InsertDiscussionCommentParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscussionComment,
		arg.DiscussionNumber,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Author,
		arg.ReplyTo,
	)
	return err
}
