// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"strings"
)

const findKnownDiscussions = `-- name: FindKnownDiscussions :many
select
    number
from
    discussions
where
    number in (/*SLICE:numbers*/?)
`

func (q *Queries) FindKnownDiscussions(ctx context.Context, numbers []int64) ([]int64, error) {
	query := findKnownDiscussions
	var queryParams []interface{}
	if len(numbers) > 0 {
		for _, v := range numbers {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:numbers*/?", strings.Repeat(",?", len(numbers))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:numbers*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var number int64
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
